plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace = "io.github.achyuki.oautopin"
    // libxposed service 102 publishes minCompileSdk 37, so the app must compile
    // against 37 or AGP fails the build. Runtime behaviour is still bounded by
    // minSdk/targetSdk below.
    compileSdk = 37

    defaultConfig {
        applicationId = "io.github.achyuki.oautopin"
        minSdk = 35
        targetSdk = 36
        versionCode = 1
        versionName = "16"
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)

    // libxposed public API. compileOnly: the framework injects it at runtime.
    compileOnly(libs.libxposed.api)
    // libxposed service. implementation: the settings Activity binds to the
    // framework through XposedServiceHelper, so these classes must be in the APK.
    implementation(libs.libxposed.service)
}
